### ISSUE TITLE
A few bugs ;)

### ISSUE THREAD

**Issue by KICKFLIP85** [SirZontax/RPGChat#1] opened 2021-01-11 14:42 UTC
Hey! I noticed some bugs when trying out your plugin, and thought I should share em with ya ;)

**Describe the bug**
1. Text not getting removed after set seconds (5)
2. NullPointerException spammed in console:
`[08:36:40 WARN]: [RPGChat] Task #62961 for RPGChat v1.2.0 generated an exception
java.lang.NullPointerException: null`
3. Text not displaying properly: they show up differently from what I write.
- "Test" shows up as "est"
it's basically just not showing up correctly, I can't seem to find a pattern
4. Multiple messages overlap each other to create some obfuscated text

**To Reproduce**
1. Run the plugin as usual
2. Use ChatManager and VentureChat

**Server (please complete the following information):**
 - 1.16.4

Thank you for creating this plugin! I've been looking for this for a good while :o

**Comment by SirZontax** [comment] 2021-01-11 15:45
Hey, to help you I have some questions.

1. Do you mean that the text stays infinity or just goes away to fast?
2. Did you use the "whisper Chat"?
3. The NullPointerException comes from one of the Task but isn't the main error code. It should be a large error message
4. The "Overlapping" should come from the failed Task and shouldn't appear if everything works fine.

The best would be if you could send me the Error Message and answer the first two questions!

Thanks for reporting your issues!

**Comment by KICKFLIP85** [comment] 2021-01-11 20:24
1. The text stays for longer than it is set in the config
2. Nope, global
3. Default, I haven't touched the configs, only looked at it

I only saw these short 2 lined NullPointerException errors being spammed in the console, I'll post another comment if I find anything else. I'll take a look at the VentureChat config and set it to the lowest priority level to see if it fixes anything.

I have a suggestion - add the option not to remove the chat on the bottom left? I do want to still use that, if possible ;)

**Comment by SirZontax** [comment] 2021-01-11 20:38
Okay.
1. Is because it had a hard coded value when it will disappear. Will be fixed with the Update tomorrow, so dw ;)
2. & 3. That shouldn't be possible. I tester it multiple times in every version, with different texts etc. and couldn't reproduce it. Did you only write: "Test"?

VentureChat has it's EventPriority Hard-coded so you can't change the Priority, maybe disable it's checks if you use RPGChat? But I'll look further into this!

I will add your suggestion in the update mention above :)

**Closed** 2021-06-20 13:08 UTC
Labels: invalid
