### ISSUE TITLE
No spaces in Normal messages

### ISSUE THREAD

**Issue by DontStarve72** [SirZontax/RPGChat#5] opened 2021-09-18 17:54 UTC
**Describe the bug**
Spaces to not appear in Normal RPGChat messages.

**To Reproduce**
1. Send a message
2. Observe that the message above one's head appears to be all one word, contradicting what is written in base chat.

**Expected behavior**
RPGChat Messages with spaces present

**Screenshots or Logs (Use https://hastebin.com/ for Logs or the Code Formatting)**
https://prnt.sc/1spy8l5

**Server (please complete the following information):**
 -  1.17.1 (Purpur version git-Purpur-1393)

**Comment by SirZontax** [comment] 2021-09-18 18:18
Hey, thanks for reporting this Bug!

I'll look into this, maybe it's caused by the new Chat-Filter-System which is still in Beta. 

Should be fixed in the next update 1.6.1

**Comment by SirZontax** [comment] 2021-09-19 11:01
Fixed with 1.6.1.

**Closed by SirZontax** 2021-09-19 11:01 UTC
Labels: bug, investigation
